# Generated by Django 5.2.7 on 2025-10-04 06:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('config_json', models.JSONField(help_text='Complete integration configuration')),
                ('source_type', models.CharField(choices=[('webhook', 'Webhook'), ('pubsub', 'Google Pub/Sub')], db_index=True, max_length=50)),
                ('webhook_path', models.CharField(blank=True, help_text='Unique webhook path (e.g., /webhook/abc123)', max_length=255, null=True, unique=True)),
                ('target_url', models.URLField(max_length=500)),
                ('target_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pubsub_project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pubsub_subscription', models.CharField(blank=True, max_length=255, null=True)),
                ('pubsub_listener_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Integration Configuration',
                'verbose_name_plural': 'Integration Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incoming_payload', models.JSONField(help_text='Payload received from source')),
                ('transformed_payload', models.JSONField(help_text='Payload after transformation')),
                ('outgoing_request', models.JSONField(help_text='Complete request sent to target API')),
                ('outgoing_response', models.JSONField(help_text='Response from target API')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('transformation_time_ms', models.IntegerField(help_text='Time to transform data', null=True)),
                ('api_call_time_ms', models.IntegerField(help_text='Time for API call', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='integrations.integrationconfiguration')),
            ],
            options={
                'verbose_name': 'Integration Run',
                'verbose_name_plural': 'Integration Runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='integration_created_df93e7_idx'), models.Index(fields=['integration', '-created_at'], name='integration_integra_53e344_idx')],
            },
        ),
    ]
