# Generated by Django 5.2.7 on 2025-10-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationrun',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('skipped', 'Skipped'), ('error', 'Error'), ('partial', 'Partial Success')], db_index=True, max_length=20),
        ),
    ]
