# Generated by Django 5.2.7 on 2025-10-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integrationrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconfiguration',
            name='pubsub_push_endpoint',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='integrationconfiguration',
            name='pubsub_topic_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
