# Generated by Django 5.2.7 on 2025-10-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_integrationconfiguration_pubsub_push_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconfiguration',
            name='pubsub_pull_interval_seconds',
            field=models.IntegerField(blank=True, default=60, help_text='Interval in seconds for pulling messages (pull mode only)', null=True),
        ),
        migrations.AddField(
            model_name='integrationconfiguration',
            name='pubsub_subscription_mode',
            field=models.CharField(blank=True, choices=[('push', 'Push'), ('pull', 'Pull')], default='push', max_length=10, null=True),
        ),
    ]
